[package]
name = "ironWeb"
version = "0.1.0"
authors = ["霧島ひなた <mastodon@mail.kirishima.cloud>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
